### ISSUE TITLE
Question: updating of ODE problem within loglik function

### ISSUE THREAD

**Issue by fkrauer** [ojal/KenyaSerology#1]
Hey Ojal and Samuel

Thanks for publishing your julia scripts and notebooks , I find them really useful to get into julia programming for ODE models. I have a question for the loglikelihoods.jl script: why is the ODE problem not updated with "remake()" within the function before solving, given that during the fitting procedure new parameter values are drawn? I thought the initial problem has to be modified when the parameter values change (as in https://diffeq.sciml.ai/stable/basics/problem/#Modification-of-problem-types), but I might be wrong. Thanks and bw, Fabienne

**Comment by SamuelBrand1** [comment]
Hi Fabienne,

Sorry about the late reply on this, I didn't notice the question (must have missed the email update).

If you're only changing the initial conditions and/or model parameters then you can use keyword arguments in the solve function, this dispatches modifications to the solver, e.g. 

`sol = solve(prob, BS3(); u0=u0, p=p, saveat = 1)
`

We did this because it just looked neat! There might be a performance penalty when solving in parallel, alluded to in the docs you link, but we found it worked ok.

**Comment by fkrauer** [comment]
No worries. I didn't even remember I asked this. That was my first baby steps with Julia 🙂 
Thanks Sam
